/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HeadscaleServiceSetTagsBody
 */
export interface HeadscaleServiceSetTagsBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof HeadscaleServiceSetTagsBody
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the HeadscaleServiceSetTagsBody interface.
 */
export function instanceOfHeadscaleServiceSetTagsBody(value: object): value is HeadscaleServiceSetTagsBody {
    return true;
}

export function HeadscaleServiceSetTagsBodyFromJSON(json: any): HeadscaleServiceSetTagsBody {
    return HeadscaleServiceSetTagsBodyFromJSONTyped(json, false);
}

export function HeadscaleServiceSetTagsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeadscaleServiceSetTagsBody {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function HeadscaleServiceSetTagsBodyToJSON(json: any): HeadscaleServiceSetTagsBody {
    return HeadscaleServiceSetTagsBodyToJSONTyped(json, false);
}

export function HeadscaleServiceSetTagsBodyToJSONTyped(value?: HeadscaleServiceSetTagsBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'],
    };
}

