/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HeadscaleServiceSetApprovedRoutesBody
 */
export interface HeadscaleServiceSetApprovedRoutesBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof HeadscaleServiceSetApprovedRoutesBody
     */
    routes?: Array<string>;
}

/**
 * Check if a given object implements the HeadscaleServiceSetApprovedRoutesBody interface.
 */
export function instanceOfHeadscaleServiceSetApprovedRoutesBody(value: object): value is HeadscaleServiceSetApprovedRoutesBody {
    return true;
}

export function HeadscaleServiceSetApprovedRoutesBodyFromJSON(json: any): HeadscaleServiceSetApprovedRoutesBody {
    return HeadscaleServiceSetApprovedRoutesBodyFromJSONTyped(json, false);
}

export function HeadscaleServiceSetApprovedRoutesBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeadscaleServiceSetApprovedRoutesBody {
    if (json == null) {
        return json;
    }
    return {
        
        'routes': json['routes'] == null ? undefined : json['routes'],
    };
}

export function HeadscaleServiceSetApprovedRoutesBodyToJSON(json: any): HeadscaleServiceSetApprovedRoutesBody {
    return HeadscaleServiceSetApprovedRoutesBodyToJSONTyped(json, false);
}

export function HeadscaleServiceSetApprovedRoutesBodyToJSONTyped(value?: HeadscaleServiceSetApprovedRoutesBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'routes': value['routes'],
    };
}

