/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ApiKey
 */
export interface V1ApiKey {
    /**
     * 
     * @type {string}
     * @memberof V1ApiKey
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ApiKey
     */
    prefix?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1ApiKey
     */
    expiration?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1ApiKey
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1ApiKey
     */
    lastSeen?: Date;
}

/**
 * Check if a given object implements the V1ApiKey interface.
 */
export function instanceOfV1ApiKey(value: object): value is V1ApiKey {
    return true;
}

export function V1ApiKeyFromJSON(json: any): V1ApiKey {
    return V1ApiKeyFromJSONTyped(json, false);
}

export function V1ApiKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ApiKey {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'expiration': json['expiration'] == null ? undefined : (new Date(json['expiration'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastSeen': json['lastSeen'] == null ? undefined : (new Date(json['lastSeen'])),
    };
}

export function V1ApiKeyToJSON(json: any): V1ApiKey {
    return V1ApiKeyToJSONTyped(json, false);
}

export function V1ApiKeyToJSONTyped(value?: V1ApiKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'prefix': value['prefix'],
        'expiration': value['expiration'] == null ? value['expiration'] : value['expiration'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'lastSeen': value['lastSeen'] == null ? value['lastSeen'] : value['lastSeen'].toISOString(),
    };
}

