/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1BackfillNodeIPsResponse
 */
export interface V1BackfillNodeIPsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1BackfillNodeIPsResponse
     */
    changes?: Array<string>;
}

/**
 * Check if a given object implements the V1BackfillNodeIPsResponse interface.
 */
export function instanceOfV1BackfillNodeIPsResponse(value: object): value is V1BackfillNodeIPsResponse {
    return true;
}

export function V1BackfillNodeIPsResponseFromJSON(json: any): V1BackfillNodeIPsResponse {
    return V1BackfillNodeIPsResponseFromJSONTyped(json, false);
}

export function V1BackfillNodeIPsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1BackfillNodeIPsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'changes': json['changes'] == null ? undefined : json['changes'],
    };
}

export function V1BackfillNodeIPsResponseToJSON(json: any): V1BackfillNodeIPsResponse {
    return V1BackfillNodeIPsResponseToJSONTyped(json, false);
}

export function V1BackfillNodeIPsResponseToJSONTyped(value?: V1BackfillNodeIPsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changes': value['changes'],
    };
}

