/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PreAuthKey } from './V1PreAuthKey';
import {
    V1PreAuthKeyFromJSON,
    V1PreAuthKeyFromJSONTyped,
    V1PreAuthKeyToJSON,
    V1PreAuthKeyToJSONTyped,
} from './V1PreAuthKey';

/**
 * 
 * @export
 * @interface V1CreatePreAuthKeyResponse
 */
export interface V1CreatePreAuthKeyResponse {
    /**
     * 
     * @type {V1PreAuthKey}
     * @memberof V1CreatePreAuthKeyResponse
     */
    preAuthKey?: V1PreAuthKey;
}

/**
 * Check if a given object implements the V1CreatePreAuthKeyResponse interface.
 */
export function instanceOfV1CreatePreAuthKeyResponse(value: object): value is V1CreatePreAuthKeyResponse {
    return true;
}

export function V1CreatePreAuthKeyResponseFromJSON(json: any): V1CreatePreAuthKeyResponse {
    return V1CreatePreAuthKeyResponseFromJSONTyped(json, false);
}

export function V1CreatePreAuthKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreatePreAuthKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'preAuthKey': json['preAuthKey'] == null ? undefined : V1PreAuthKeyFromJSON(json['preAuthKey']),
    };
}

export function V1CreatePreAuthKeyResponseToJSON(json: any): V1CreatePreAuthKeyResponse {
    return V1CreatePreAuthKeyResponseToJSONTyped(json, false);
}

export function V1CreatePreAuthKeyResponseToJSONTyped(value?: V1CreatePreAuthKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'preAuthKey': V1PreAuthKeyToJSON(value['preAuthKey']),
    };
}

