/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1User } from './V1User';
import {
    V1UserFromJSON,
    V1UserFromJSONTyped,
    V1UserToJSON,
    V1UserToJSONTyped,
} from './V1User';

/**
 * 
 * @export
 * @interface V1CreateUserResponse
 */
export interface V1CreateUserResponse {
    /**
     * 
     * @type {V1User}
     * @memberof V1CreateUserResponse
     */
    user?: V1User;
}

/**
 * Check if a given object implements the V1CreateUserResponse interface.
 */
export function instanceOfV1CreateUserResponse(value: object): value is V1CreateUserResponse {
    return true;
}

export function V1CreateUserResponseFromJSON(json: any): V1CreateUserResponse {
    return V1CreateUserResponseFromJSONTyped(json, false);
}

export function V1CreateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : V1UserFromJSON(json['user']),
    };
}

export function V1CreateUserResponseToJSON(json: any): V1CreateUserResponse {
    return V1CreateUserResponseToJSONTyped(json, false);
}

export function V1CreateUserResponseToJSONTyped(value?: V1CreateUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': V1UserToJSON(value['user']),
    };
}

