/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateApiKeyRequest
 */
export interface V1CreateApiKeyRequest {
    /**
     * 
     * @type {Date}
     * @memberof V1CreateApiKeyRequest
     */
    expiration?: Date;
}

/**
 * Check if a given object implements the V1CreateApiKeyRequest interface.
 */
export function instanceOfV1CreateApiKeyRequest(value: object): value is V1CreateApiKeyRequest {
    return true;
}

export function V1CreateApiKeyRequestFromJSON(json: any): V1CreateApiKeyRequest {
    return V1CreateApiKeyRequestFromJSONTyped(json, false);
}

export function V1CreateApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expiration': json['expiration'] == null ? undefined : (new Date(json['expiration'])),
    };
}

export function V1CreateApiKeyRequestToJSON(json: any): V1CreateApiKeyRequest {
    return V1CreateApiKeyRequestToJSONTyped(json, false);
}

export function V1CreateApiKeyRequestToJSONTyped(value?: V1CreateApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expiration': value['expiration'] == null ? value['expiration'] : value['expiration'].toISOString(),
    };
}

