/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateUserRequest
 */
export interface V1CreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    pictureUrl?: string;
}

/**
 * Check if a given object implements the V1CreateUserRequest interface.
 */
export function instanceOfV1CreateUserRequest(value: object): value is V1CreateUserRequest {
    return true;
}

export function V1CreateUserRequestFromJSON(json: any): V1CreateUserRequest {
    return V1CreateUserRequestFromJSONTyped(json, false);
}

export function V1CreateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'email': json['email'] == null ? undefined : json['email'],
        'pictureUrl': json['pictureUrl'] == null ? undefined : json['pictureUrl'],
    };
}

export function V1CreateUserRequestToJSON(json: any): V1CreateUserRequest {
    return V1CreateUserRequestToJSONTyped(json, false);
}

export function V1CreateUserRequestToJSONTyped(value?: V1CreateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'displayName': value['displayName'],
        'email': value['email'],
        'pictureUrl': value['pictureUrl'],
    };
}

