/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ExpirePreAuthKeyRequest
 */
export interface V1ExpirePreAuthKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof V1ExpirePreAuthKeyRequest
     */
    id?: string;
}

/**
 * Check if a given object implements the V1ExpirePreAuthKeyRequest interface.
 */
export function instanceOfV1ExpirePreAuthKeyRequest(value: object): value is V1ExpirePreAuthKeyRequest {
    return true;
}

export function V1ExpirePreAuthKeyRequestFromJSON(json: any): V1ExpirePreAuthKeyRequest {
    return V1ExpirePreAuthKeyRequestFromJSONTyped(json, false);
}

export function V1ExpirePreAuthKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ExpirePreAuthKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function V1ExpirePreAuthKeyRequestToJSON(json: any): V1ExpirePreAuthKeyRequest {
    return V1ExpirePreAuthKeyRequestToJSONTyped(json, false);
}

export function V1ExpirePreAuthKeyRequestToJSONTyped(value?: V1ExpirePreAuthKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

