/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ExpireApiKeyRequest
 */
export interface V1ExpireApiKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof V1ExpireApiKeyRequest
     */
    prefix?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ExpireApiKeyRequest
     */
    id?: string;
}

/**
 * Check if a given object implements the V1ExpireApiKeyRequest interface.
 */
export function instanceOfV1ExpireApiKeyRequest(value: object): value is V1ExpireApiKeyRequest {
    return true;
}

export function V1ExpireApiKeyRequestFromJSON(json: any): V1ExpireApiKeyRequest {
    return V1ExpireApiKeyRequestFromJSONTyped(json, false);
}

export function V1ExpireApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ExpireApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function V1ExpireApiKeyRequestToJSON(json: any): V1ExpireApiKeyRequest {
    return V1ExpireApiKeyRequestToJSONTyped(json, false);
}

export function V1ExpireApiKeyRequestToJSONTyped(value?: V1ExpireApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prefix': value['prefix'],
        'id': value['id'],
    };
}

