/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1HealthResponse
 */
export interface V1HealthResponse {
    /**
     * 
     * @type {boolean}
     * @memberof V1HealthResponse
     */
    databaseConnectivity?: boolean;
}

/**
 * Check if a given object implements the V1HealthResponse interface.
 */
export function instanceOfV1HealthResponse(value: object): value is V1HealthResponse {
    return true;
}

export function V1HealthResponseFromJSON(json: any): V1HealthResponse {
    return V1HealthResponseFromJSONTyped(json, false);
}

export function V1HealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1HealthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'databaseConnectivity': json['databaseConnectivity'] == null ? undefined : json['databaseConnectivity'],
    };
}

export function V1HealthResponseToJSON(json: any): V1HealthResponse {
    return V1HealthResponseToJSONTyped(json, false);
}

export function V1HealthResponseToJSONTyped(value?: V1HealthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'databaseConnectivity': value['databaseConnectivity'],
    };
}

