/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ApiKey } from './V1ApiKey';
import {
    V1ApiKeyFromJSON,
    V1ApiKeyFromJSONTyped,
    V1ApiKeyToJSON,
    V1ApiKeyToJSONTyped,
} from './V1ApiKey';

/**
 * 
 * @export
 * @interface V1ListApiKeysResponse
 */
export interface V1ListApiKeysResponse {
    /**
     * 
     * @type {Array<V1ApiKey>}
     * @memberof V1ListApiKeysResponse
     */
    apiKeys?: Array<V1ApiKey>;
}

/**
 * Check if a given object implements the V1ListApiKeysResponse interface.
 */
export function instanceOfV1ListApiKeysResponse(value: object): value is V1ListApiKeysResponse {
    return true;
}

export function V1ListApiKeysResponseFromJSON(json: any): V1ListApiKeysResponse {
    return V1ListApiKeysResponseFromJSONTyped(json, false);
}

export function V1ListApiKeysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListApiKeysResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKeys': json['apiKeys'] == null ? undefined : ((json['apiKeys'] as Array<any>).map(V1ApiKeyFromJSON)),
    };
}

export function V1ListApiKeysResponseToJSON(json: any): V1ListApiKeysResponse {
    return V1ListApiKeysResponseToJSONTyped(json, false);
}

export function V1ListApiKeysResponseToJSONTyped(value?: V1ListApiKeysResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKeys': value['apiKeys'] == null ? undefined : ((value['apiKeys'] as Array<any>).map(V1ApiKeyToJSON)),
    };
}

