/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1User } from './V1User';
import {
    V1UserFromJSON,
    V1UserFromJSONTyped,
    V1UserToJSON,
    V1UserToJSONTyped,
} from './V1User';

/**
 * 
 * @export
 * @interface V1ListUsersResponse
 */
export interface V1ListUsersResponse {
    /**
     * 
     * @type {Array<V1User>}
     * @memberof V1ListUsersResponse
     */
    users?: Array<V1User>;
}

/**
 * Check if a given object implements the V1ListUsersResponse interface.
 */
export function instanceOfV1ListUsersResponse(value: object): value is V1ListUsersResponse {
    return true;
}

export function V1ListUsersResponseFromJSON(json: any): V1ListUsersResponse {
    return V1ListUsersResponseFromJSONTyped(json, false);
}

export function V1ListUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListUsersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(V1UserFromJSON)),
    };
}

export function V1ListUsersResponseToJSON(json: any): V1ListUsersResponse {
    return V1ListUsersResponseToJSONTyped(json, false);
}

export function V1ListUsersResponseToJSONTyped(value?: V1ListUsersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(V1UserToJSON)),
    };
}

