/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PreAuthKey } from './V1PreAuthKey';
import {
    V1PreAuthKeyFromJSON,
    V1PreAuthKeyFromJSONTyped,
    V1PreAuthKeyToJSON,
    V1PreAuthKeyToJSONTyped,
} from './V1PreAuthKey';

/**
 * 
 * @export
 * @interface V1ListPreAuthKeysResponse
 */
export interface V1ListPreAuthKeysResponse {
    /**
     * 
     * @type {Array<V1PreAuthKey>}
     * @memberof V1ListPreAuthKeysResponse
     */
    preAuthKeys?: Array<V1PreAuthKey>;
}

/**
 * Check if a given object implements the V1ListPreAuthKeysResponse interface.
 */
export function instanceOfV1ListPreAuthKeysResponse(value: object): value is V1ListPreAuthKeysResponse {
    return true;
}

export function V1ListPreAuthKeysResponseFromJSON(json: any): V1ListPreAuthKeysResponse {
    return V1ListPreAuthKeysResponseFromJSONTyped(json, false);
}

export function V1ListPreAuthKeysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListPreAuthKeysResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'preAuthKeys': json['preAuthKeys'] == null ? undefined : ((json['preAuthKeys'] as Array<any>).map(V1PreAuthKeyFromJSON)),
    };
}

export function V1ListPreAuthKeysResponseToJSON(json: any): V1ListPreAuthKeysResponse {
    return V1ListPreAuthKeysResponseToJSONTyped(json, false);
}

export function V1ListPreAuthKeysResponseToJSONTyped(value?: V1ListPreAuthKeysResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'preAuthKeys': value['preAuthKeys'] == null ? undefined : ((value['preAuthKeys'] as Array<any>).map(V1PreAuthKeyToJSON)),
    };
}

