/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1User } from './V1User';
import {
    V1UserFromJSON,
    V1UserFromJSONTyped,
    V1UserToJSON,
    V1UserToJSONTyped,
} from './V1User';

/**
 * 
 * @export
 * @interface V1PreAuthKey
 */
export interface V1PreAuthKey {
    /**
     * 
     * @type {V1User}
     * @memberof V1PreAuthKey
     */
    user?: V1User;
    /**
     * 
     * @type {string}
     * @memberof V1PreAuthKey
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PreAuthKey
     */
    key?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1PreAuthKey
     */
    reusable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V1PreAuthKey
     */
    ephemeral?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V1PreAuthKey
     */
    used?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof V1PreAuthKey
     */
    expiration?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1PreAuthKey
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1PreAuthKey
     */
    aclTags?: Array<string>;
}

/**
 * Check if a given object implements the V1PreAuthKey interface.
 */
export function instanceOfV1PreAuthKey(value: object): value is V1PreAuthKey {
    return true;
}

export function V1PreAuthKeyFromJSON(json: any): V1PreAuthKey {
    return V1PreAuthKeyFromJSONTyped(json, false);
}

export function V1PreAuthKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PreAuthKey {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : V1UserFromJSON(json['user']),
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'reusable': json['reusable'] == null ? undefined : json['reusable'],
        'ephemeral': json['ephemeral'] == null ? undefined : json['ephemeral'],
        'used': json['used'] == null ? undefined : json['used'],
        'expiration': json['expiration'] == null ? undefined : (new Date(json['expiration'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'aclTags': json['aclTags'] == null ? undefined : json['aclTags'],
    };
}

export function V1PreAuthKeyToJSON(json: any): V1PreAuthKey {
    return V1PreAuthKeyToJSONTyped(json, false);
}

export function V1PreAuthKeyToJSONTyped(value?: V1PreAuthKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': V1UserToJSON(value['user']),
        'id': value['id'],
        'key': value['key'],
        'reusable': value['reusable'],
        'ephemeral': value['ephemeral'],
        'used': value['used'],
        'expiration': value['expiration'] == null ? value['expiration'] : value['expiration'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'aclTags': value['aclTags'],
    };
}

