/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1RegisterMethod = {
    RegisterMethodUnspecified: 'REGISTER_METHOD_UNSPECIFIED',
    RegisterMethodAuthKey: 'REGISTER_METHOD_AUTH_KEY',
    RegisterMethodCli: 'REGISTER_METHOD_CLI',
    RegisterMethodOidc: 'REGISTER_METHOD_OIDC'
} as const;
export type V1RegisterMethod = typeof V1RegisterMethod[keyof typeof V1RegisterMethod];


export function instanceOfV1RegisterMethod(value: any): boolean {
    for (const key in V1RegisterMethod) {
        if (Object.prototype.hasOwnProperty.call(V1RegisterMethod, key)) {
            if (V1RegisterMethod[key as keyof typeof V1RegisterMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1RegisterMethodFromJSON(json: any): V1RegisterMethod {
    return V1RegisterMethodFromJSONTyped(json, false);
}

export function V1RegisterMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1RegisterMethod {
    return json as V1RegisterMethod;
}

export function V1RegisterMethodToJSON(value?: V1RegisterMethod | null): any {
    return value as any;
}

export function V1RegisterMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): V1RegisterMethod {
    return value as V1RegisterMethod;
}

