/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1SetPolicyRequest
 */
export interface V1SetPolicyRequest {
    /**
     * 
     * @type {string}
     * @memberof V1SetPolicyRequest
     */
    policy?: string;
}

/**
 * Check if a given object implements the V1SetPolicyRequest interface.
 */
export function instanceOfV1SetPolicyRequest(value: object): value is V1SetPolicyRequest {
    return true;
}

export function V1SetPolicyRequestFromJSON(json: any): V1SetPolicyRequest {
    return V1SetPolicyRequestFromJSONTyped(json, false);
}

export function V1SetPolicyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SetPolicyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'policy': json['policy'] == null ? undefined : json['policy'],
    };
}

export function V1SetPolicyRequestToJSON(json: any): V1SetPolicyRequest {
    return V1SetPolicyRequestToJSONTyped(json, false);
}

export function V1SetPolicyRequestToJSONTyped(value?: V1SetPolicyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'policy': value['policy'],
    };
}

