/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Node } from './V1Node';
import {
    V1NodeFromJSON,
    V1NodeFromJSONTyped,
    V1NodeToJSON,
    V1NodeToJSONTyped,
} from './V1Node';

/**
 * 
 * @export
 * @interface V1SetTagsResponse
 */
export interface V1SetTagsResponse {
    /**
     * 
     * @type {V1Node}
     * @memberof V1SetTagsResponse
     */
    node?: V1Node;
}

/**
 * Check if a given object implements the V1SetTagsResponse interface.
 */
export function instanceOfV1SetTagsResponse(value: object): value is V1SetTagsResponse {
    return true;
}

export function V1SetTagsResponseFromJSON(json: any): V1SetTagsResponse {
    return V1SetTagsResponseFromJSONTyped(json, false);
}

export function V1SetTagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SetTagsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'] == null ? undefined : V1NodeFromJSON(json['node']),
    };
}

export function V1SetTagsResponseToJSON(json: any): V1SetTagsResponse {
    return V1SetTagsResponseToJSONTyped(json, false);
}

export function V1SetTagsResponseToJSONTyped(value?: V1SetTagsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node': V1NodeToJSON(value['node']),
    };
}

