/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1SetPolicyResponse
 */
export interface V1SetPolicyResponse {
    /**
     * 
     * @type {string}
     * @memberof V1SetPolicyResponse
     */
    policy?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1SetPolicyResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the V1SetPolicyResponse interface.
 */
export function instanceOfV1SetPolicyResponse(value: object): value is V1SetPolicyResponse {
    return true;
}

export function V1SetPolicyResponseFromJSON(json: any): V1SetPolicyResponse {
    return V1SetPolicyResponseFromJSONTyped(json, false);
}

export function V1SetPolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SetPolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'policy': json['policy'] == null ? undefined : json['policy'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function V1SetPolicyResponseToJSON(json: any): V1SetPolicyResponse {
    return V1SetPolicyResponseToJSONTyped(json, false);
}

export function V1SetPolicyResponseToJSONTyped(value?: V1SetPolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'policy': value['policy'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

