/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1User
 */
export interface V1User {
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1User
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    providerId?: string;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    profilePicUrl?: string;
}

/**
 * Check if a given object implements the V1User interface.
 */
export function instanceOfV1User(value: object): value is V1User {
    return true;
}

export function V1UserFromJSON(json: any): V1User {
    return V1UserFromJSONTyped(json, false);
}

export function V1UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'email': json['email'] == null ? undefined : json['email'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'profilePicUrl': json['profilePicUrl'] == null ? undefined : json['profilePicUrl'],
    };
}

export function V1UserToJSON(json: any): V1User {
    return V1UserToJSONTyped(json, false);
}

export function V1UserToJSONTyped(value?: V1User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'displayName': value['displayName'],
        'email': value['email'],
        'providerId': value['providerId'],
        'provider': value['provider'],
        'profilePicUrl': value['profilePicUrl'],
    };
}

