/* tslint:disable */
/* eslint-disable */
/**
 * headscale/v1/headscale.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HeadscaleServiceSetApprovedRoutesBody,
    HeadscaleServiceSetApprovedRoutesBodyFromJSON,
    HeadscaleServiceSetApprovedRoutesBodyToJSON,
} from '../models/HeadscaleServiceSetApprovedRoutesBody';
import {
    type HeadscaleServiceSetTagsBody,
    HeadscaleServiceSetTagsBodyFromJSON,
    HeadscaleServiceSetTagsBodyToJSON,
} from '../models/HeadscaleServiceSetTagsBody';
import {
    type RpcStatus,
    RpcStatusFromJSON,
    RpcStatusToJSON,
} from '../models/RpcStatus';
import {
    type V1BackfillNodeIPsResponse,
    V1BackfillNodeIPsResponseFromJSON,
    V1BackfillNodeIPsResponseToJSON,
} from '../models/V1BackfillNodeIPsResponse';
import {
    type V1CreateApiKeyRequest,
    V1CreateApiKeyRequestFromJSON,
    V1CreateApiKeyRequestToJSON,
} from '../models/V1CreateApiKeyRequest';
import {
    type V1CreateApiKeyResponse,
    V1CreateApiKeyResponseFromJSON,
    V1CreateApiKeyResponseToJSON,
} from '../models/V1CreateApiKeyResponse';
import {
    type V1CreatePreAuthKeyRequest,
    V1CreatePreAuthKeyRequestFromJSON,
    V1CreatePreAuthKeyRequestToJSON,
} from '../models/V1CreatePreAuthKeyRequest';
import {
    type V1CreatePreAuthKeyResponse,
    V1CreatePreAuthKeyResponseFromJSON,
    V1CreatePreAuthKeyResponseToJSON,
} from '../models/V1CreatePreAuthKeyResponse';
import {
    type V1CreateUserRequest,
    V1CreateUserRequestFromJSON,
    V1CreateUserRequestToJSON,
} from '../models/V1CreateUserRequest';
import {
    type V1CreateUserResponse,
    V1CreateUserResponseFromJSON,
    V1CreateUserResponseToJSON,
} from '../models/V1CreateUserResponse';
import {
    type V1DebugCreateNodeRequest,
    V1DebugCreateNodeRequestFromJSON,
    V1DebugCreateNodeRequestToJSON,
} from '../models/V1DebugCreateNodeRequest';
import {
    type V1DebugCreateNodeResponse,
    V1DebugCreateNodeResponseFromJSON,
    V1DebugCreateNodeResponseToJSON,
} from '../models/V1DebugCreateNodeResponse';
import {
    type V1ExpireApiKeyRequest,
    V1ExpireApiKeyRequestFromJSON,
    V1ExpireApiKeyRequestToJSON,
} from '../models/V1ExpireApiKeyRequest';
import {
    type V1ExpireNodeResponse,
    V1ExpireNodeResponseFromJSON,
    V1ExpireNodeResponseToJSON,
} from '../models/V1ExpireNodeResponse';
import {
    type V1ExpirePreAuthKeyRequest,
    V1ExpirePreAuthKeyRequestFromJSON,
    V1ExpirePreAuthKeyRequestToJSON,
} from '../models/V1ExpirePreAuthKeyRequest';
import {
    type V1GetNodeResponse,
    V1GetNodeResponseFromJSON,
    V1GetNodeResponseToJSON,
} from '../models/V1GetNodeResponse';
import {
    type V1GetPolicyResponse,
    V1GetPolicyResponseFromJSON,
    V1GetPolicyResponseToJSON,
} from '../models/V1GetPolicyResponse';
import {
    type V1HealthResponse,
    V1HealthResponseFromJSON,
    V1HealthResponseToJSON,
} from '../models/V1HealthResponse';
import {
    type V1ListApiKeysResponse,
    V1ListApiKeysResponseFromJSON,
    V1ListApiKeysResponseToJSON,
} from '../models/V1ListApiKeysResponse';
import {
    type V1ListNodesResponse,
    V1ListNodesResponseFromJSON,
    V1ListNodesResponseToJSON,
} from '../models/V1ListNodesResponse';
import {
    type V1ListPreAuthKeysResponse,
    V1ListPreAuthKeysResponseFromJSON,
    V1ListPreAuthKeysResponseToJSON,
} from '../models/V1ListPreAuthKeysResponse';
import {
    type V1ListUsersResponse,
    V1ListUsersResponseFromJSON,
    V1ListUsersResponseToJSON,
} from '../models/V1ListUsersResponse';
import {
    type V1RegisterNodeResponse,
    V1RegisterNodeResponseFromJSON,
    V1RegisterNodeResponseToJSON,
} from '../models/V1RegisterNodeResponse';
import {
    type V1RenameNodeResponse,
    V1RenameNodeResponseFromJSON,
    V1RenameNodeResponseToJSON,
} from '../models/V1RenameNodeResponse';
import {
    type V1RenameUserResponse,
    V1RenameUserResponseFromJSON,
    V1RenameUserResponseToJSON,
} from '../models/V1RenameUserResponse';
import {
    type V1SetApprovedRoutesResponse,
    V1SetApprovedRoutesResponseFromJSON,
    V1SetApprovedRoutesResponseToJSON,
} from '../models/V1SetApprovedRoutesResponse';
import {
    type V1SetPolicyRequest,
    V1SetPolicyRequestFromJSON,
    V1SetPolicyRequestToJSON,
} from '../models/V1SetPolicyRequest';
import {
    type V1SetPolicyResponse,
    V1SetPolicyResponseFromJSON,
    V1SetPolicyResponseToJSON,
} from '../models/V1SetPolicyResponse';
import {
    type V1SetTagsResponse,
    V1SetTagsResponseFromJSON,
    V1SetTagsResponseToJSON,
} from '../models/V1SetTagsResponse';

export interface HeadscaleServiceBackfillNodeIPsRequest {
    confirmed?: boolean;
}

export interface HeadscaleServiceCreateApiKeyRequest {
    body: V1CreateApiKeyRequest;
}

export interface HeadscaleServiceCreatePreAuthKeyRequest {
    body: V1CreatePreAuthKeyRequest;
}

export interface HeadscaleServiceCreateUserRequest {
    body: V1CreateUserRequest;
}

export interface HeadscaleServiceDebugCreateNodeRequest {
    body: V1DebugCreateNodeRequest;
}

export interface HeadscaleServiceDeleteApiKeyRequest {
    prefix: string;
    id?: string;
}

export interface HeadscaleServiceDeleteNodeRequest {
    nodeId: string;
}

export interface HeadscaleServiceDeletePreAuthKeyRequest {
    id?: string;
}

export interface HeadscaleServiceDeleteUserRequest {
    id: string;
}

export interface HeadscaleServiceExpireApiKeyRequest {
    body: V1ExpireApiKeyRequest;
}

export interface HeadscaleServiceExpireNodeRequest {
    nodeId: string;
    expiry?: Date;
}

export interface HeadscaleServiceExpirePreAuthKeyRequest {
    body: V1ExpirePreAuthKeyRequest;
}

export interface HeadscaleServiceGetNodeRequest {
    nodeId: string;
}

export interface HeadscaleServiceListNodesRequest {
    user?: string;
}

export interface HeadscaleServiceListUsersRequest {
    id?: string;
    name?: string;
    email?: string;
}

export interface HeadscaleServiceRegisterNodeRequest {
    user?: string;
    key?: string;
}

export interface HeadscaleServiceRenameNodeRequest {
    nodeId: string;
    newName: string;
}

export interface HeadscaleServiceRenameUserRequest {
    oldId: string;
    newName: string;
}

export interface HeadscaleServiceSetApprovedRoutesRequest {
    nodeId: string;
    body: HeadscaleServiceSetApprovedRoutesBody;
}

export interface HeadscaleServiceSetPolicyRequest {
    body: V1SetPolicyRequest;
}

export interface HeadscaleServiceSetTagsRequest {
    nodeId: string;
    body: HeadscaleServiceSetTagsBody;
}

/**
 * 
 */
export class HeadscaleServiceApi extends runtime.BaseAPI {

    /**
     * Creates request options for headscaleServiceBackfillNodeIPs without sending the request
     */
    async headscaleServiceBackfillNodeIPsRequestOpts(requestParameters: HeadscaleServiceBackfillNodeIPsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['confirmed'] != null) {
            queryParameters['confirmed'] = requestParameters['confirmed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/node/backfillips`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceBackfillNodeIPsRaw(requestParameters: HeadscaleServiceBackfillNodeIPsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1BackfillNodeIPsResponse>> {
        const requestOptions = await this.headscaleServiceBackfillNodeIPsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1BackfillNodeIPsResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceBackfillNodeIPs(requestParameters: HeadscaleServiceBackfillNodeIPsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1BackfillNodeIPsResponse> {
        const response = await this.headscaleServiceBackfillNodeIPsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceCreateApiKey without sending the request
     */
    async headscaleServiceCreateApiKeyRequestOpts(requestParameters: HeadscaleServiceCreateApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceCreateApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/apikey`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1CreateApiKeyRequestToJSON(requestParameters['body']),
        };
    }

    /**
     * --- ApiKeys start ---
     */
    async headscaleServiceCreateApiKeyRaw(requestParameters: HeadscaleServiceCreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1CreateApiKeyResponse>> {
        const requestOptions = await this.headscaleServiceCreateApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1CreateApiKeyResponseFromJSON(jsonValue));
    }

    /**
     * --- ApiKeys start ---
     */
    async headscaleServiceCreateApiKey(requestParameters: HeadscaleServiceCreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1CreateApiKeyResponse> {
        const response = await this.headscaleServiceCreateApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceCreatePreAuthKey without sending the request
     */
    async headscaleServiceCreatePreAuthKeyRequestOpts(requestParameters: HeadscaleServiceCreatePreAuthKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceCreatePreAuthKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/preauthkey`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1CreatePreAuthKeyRequestToJSON(requestParameters['body']),
        };
    }

    /**
     * --- PreAuthKeys start ---
     */
    async headscaleServiceCreatePreAuthKeyRaw(requestParameters: HeadscaleServiceCreatePreAuthKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1CreatePreAuthKeyResponse>> {
        const requestOptions = await this.headscaleServiceCreatePreAuthKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1CreatePreAuthKeyResponseFromJSON(jsonValue));
    }

    /**
     * --- PreAuthKeys start ---
     */
    async headscaleServiceCreatePreAuthKey(requestParameters: HeadscaleServiceCreatePreAuthKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1CreatePreAuthKeyResponse> {
        const response = await this.headscaleServiceCreatePreAuthKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceCreateUser without sending the request
     */
    async headscaleServiceCreateUserRequestOpts(requestParameters: HeadscaleServiceCreateUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceCreateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/user`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1CreateUserRequestToJSON(requestParameters['body']),
        };
    }

    /**
     * --- User start ---
     */
    async headscaleServiceCreateUserRaw(requestParameters: HeadscaleServiceCreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1CreateUserResponse>> {
        const requestOptions = await this.headscaleServiceCreateUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1CreateUserResponseFromJSON(jsonValue));
    }

    /**
     * --- User start ---
     */
    async headscaleServiceCreateUser(requestParameters: HeadscaleServiceCreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1CreateUserResponse> {
        const response = await this.headscaleServiceCreateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceDebugCreateNode without sending the request
     */
    async headscaleServiceDebugCreateNodeRequestOpts(requestParameters: HeadscaleServiceDebugCreateNodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceDebugCreateNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/debug/node`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1DebugCreateNodeRequestToJSON(requestParameters['body']),
        };
    }

    /**
     * --- Node start ---
     */
    async headscaleServiceDebugCreateNodeRaw(requestParameters: HeadscaleServiceDebugCreateNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1DebugCreateNodeResponse>> {
        const requestOptions = await this.headscaleServiceDebugCreateNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1DebugCreateNodeResponseFromJSON(jsonValue));
    }

    /**
     * --- Node start ---
     */
    async headscaleServiceDebugCreateNode(requestParameters: HeadscaleServiceDebugCreateNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1DebugCreateNodeResponse> {
        const response = await this.headscaleServiceDebugCreateNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceDeleteApiKey without sending the request
     */
    async headscaleServiceDeleteApiKeyRequestOpts(requestParameters: HeadscaleServiceDeleteApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prefix'] == null) {
            throw new runtime.RequiredError(
                'prefix',
                'Required parameter "prefix" was null or undefined when calling headscaleServiceDeleteApiKey().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/apikey/{prefix}`;
        urlPath = urlPath.replace('{prefix}', encodeURIComponent(String(requestParameters['prefix'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceDeleteApiKeyRaw(requestParameters: HeadscaleServiceDeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.headscaleServiceDeleteApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async headscaleServiceDeleteApiKey(requestParameters: HeadscaleServiceDeleteApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.headscaleServiceDeleteApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceDeleteNode without sending the request
     */
    async headscaleServiceDeleteNodeRequestOpts(requestParameters: HeadscaleServiceDeleteNodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling headscaleServiceDeleteNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/node/{nodeId}`;
        urlPath = urlPath.replace('{nodeId}', encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceDeleteNodeRaw(requestParameters: HeadscaleServiceDeleteNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.headscaleServiceDeleteNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async headscaleServiceDeleteNode(requestParameters: HeadscaleServiceDeleteNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.headscaleServiceDeleteNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceDeletePreAuthKey without sending the request
     */
    async headscaleServiceDeletePreAuthKeyRequestOpts(requestParameters: HeadscaleServiceDeletePreAuthKeyRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/preauthkey`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceDeletePreAuthKeyRaw(requestParameters: HeadscaleServiceDeletePreAuthKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.headscaleServiceDeletePreAuthKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async headscaleServiceDeletePreAuthKey(requestParameters: HeadscaleServiceDeletePreAuthKeyRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.headscaleServiceDeletePreAuthKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceDeleteUser without sending the request
     */
    async headscaleServiceDeleteUserRequestOpts(requestParameters: HeadscaleServiceDeleteUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling headscaleServiceDeleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceDeleteUserRaw(requestParameters: HeadscaleServiceDeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.headscaleServiceDeleteUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async headscaleServiceDeleteUser(requestParameters: HeadscaleServiceDeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.headscaleServiceDeleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceExpireApiKey without sending the request
     */
    async headscaleServiceExpireApiKeyRequestOpts(requestParameters: HeadscaleServiceExpireApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceExpireApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/apikey/expire`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1ExpireApiKeyRequestToJSON(requestParameters['body']),
        };
    }

    /**
     */
    async headscaleServiceExpireApiKeyRaw(requestParameters: HeadscaleServiceExpireApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.headscaleServiceExpireApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async headscaleServiceExpireApiKey(requestParameters: HeadscaleServiceExpireApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.headscaleServiceExpireApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceExpireNode without sending the request
     */
    async headscaleServiceExpireNodeRequestOpts(requestParameters: HeadscaleServiceExpireNodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling headscaleServiceExpireNode().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expiry'] != null) {
            queryParameters['expiry'] = (requestParameters['expiry'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/node/{nodeId}/expire`;
        urlPath = urlPath.replace('{nodeId}', encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceExpireNodeRaw(requestParameters: HeadscaleServiceExpireNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1ExpireNodeResponse>> {
        const requestOptions = await this.headscaleServiceExpireNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1ExpireNodeResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceExpireNode(requestParameters: HeadscaleServiceExpireNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1ExpireNodeResponse> {
        const response = await this.headscaleServiceExpireNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceExpirePreAuthKey without sending the request
     */
    async headscaleServiceExpirePreAuthKeyRequestOpts(requestParameters: HeadscaleServiceExpirePreAuthKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceExpirePreAuthKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/preauthkey/expire`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1ExpirePreAuthKeyRequestToJSON(requestParameters['body']),
        };
    }

    /**
     */
    async headscaleServiceExpirePreAuthKeyRaw(requestParameters: HeadscaleServiceExpirePreAuthKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.headscaleServiceExpirePreAuthKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async headscaleServiceExpirePreAuthKey(requestParameters: HeadscaleServiceExpirePreAuthKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.headscaleServiceExpirePreAuthKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceGetNode without sending the request
     */
    async headscaleServiceGetNodeRequestOpts(requestParameters: HeadscaleServiceGetNodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling headscaleServiceGetNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/node/{nodeId}`;
        urlPath = urlPath.replace('{nodeId}', encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceGetNodeRaw(requestParameters: HeadscaleServiceGetNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1GetNodeResponse>> {
        const requestOptions = await this.headscaleServiceGetNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1GetNodeResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceGetNode(requestParameters: HeadscaleServiceGetNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1GetNodeResponse> {
        const response = await this.headscaleServiceGetNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceGetPolicy without sending the request
     */
    async headscaleServiceGetPolicyRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/policy`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * --- Policy start ---
     */
    async headscaleServiceGetPolicyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1GetPolicyResponse>> {
        const requestOptions = await this.headscaleServiceGetPolicyRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1GetPolicyResponseFromJSON(jsonValue));
    }

    /**
     * --- Policy start ---
     */
    async headscaleServiceGetPolicy(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1GetPolicyResponse> {
        const response = await this.headscaleServiceGetPolicyRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceHealth without sending the request
     */
    async headscaleServiceHealthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * --- Health start ---
     */
    async headscaleServiceHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1HealthResponse>> {
        const requestOptions = await this.headscaleServiceHealthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1HealthResponseFromJSON(jsonValue));
    }

    /**
     * --- Health start ---
     */
    async headscaleServiceHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1HealthResponse> {
        const response = await this.headscaleServiceHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceListApiKeys without sending the request
     */
    async headscaleServiceListApiKeysRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/apikey`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceListApiKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1ListApiKeysResponse>> {
        const requestOptions = await this.headscaleServiceListApiKeysRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1ListApiKeysResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceListApiKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1ListApiKeysResponse> {
        const response = await this.headscaleServiceListApiKeysRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceListNodes without sending the request
     */
    async headscaleServiceListNodesRequestOpts(requestParameters: HeadscaleServiceListNodesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['user'] != null) {
            queryParameters['user'] = requestParameters['user'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/node`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceListNodesRaw(requestParameters: HeadscaleServiceListNodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1ListNodesResponse>> {
        const requestOptions = await this.headscaleServiceListNodesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1ListNodesResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceListNodes(requestParameters: HeadscaleServiceListNodesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1ListNodesResponse> {
        const response = await this.headscaleServiceListNodesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceListPreAuthKeys without sending the request
     */
    async headscaleServiceListPreAuthKeysRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/preauthkey`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceListPreAuthKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1ListPreAuthKeysResponse>> {
        const requestOptions = await this.headscaleServiceListPreAuthKeysRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1ListPreAuthKeysResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceListPreAuthKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1ListPreAuthKeysResponse> {
        const response = await this.headscaleServiceListPreAuthKeysRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceListUsers without sending the request
     */
    async headscaleServiceListUsersRequestOpts(requestParameters: HeadscaleServiceListUsersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceListUsersRaw(requestParameters: HeadscaleServiceListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1ListUsersResponse>> {
        const requestOptions = await this.headscaleServiceListUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1ListUsersResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceListUsers(requestParameters: HeadscaleServiceListUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1ListUsersResponse> {
        const response = await this.headscaleServiceListUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceRegisterNode without sending the request
     */
    async headscaleServiceRegisterNodeRequestOpts(requestParameters: HeadscaleServiceRegisterNodeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['user'] != null) {
            queryParameters['user'] = requestParameters['user'];
        }

        if (requestParameters['key'] != null) {
            queryParameters['key'] = requestParameters['key'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/node/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceRegisterNodeRaw(requestParameters: HeadscaleServiceRegisterNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1RegisterNodeResponse>> {
        const requestOptions = await this.headscaleServiceRegisterNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1RegisterNodeResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceRegisterNode(requestParameters: HeadscaleServiceRegisterNodeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1RegisterNodeResponse> {
        const response = await this.headscaleServiceRegisterNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceRenameNode without sending the request
     */
    async headscaleServiceRenameNodeRequestOpts(requestParameters: HeadscaleServiceRenameNodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling headscaleServiceRenameNode().'
            );
        }

        if (requestParameters['newName'] == null) {
            throw new runtime.RequiredError(
                'newName',
                'Required parameter "newName" was null or undefined when calling headscaleServiceRenameNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/node/{nodeId}/rename/{newName}`;
        urlPath = urlPath.replace('{nodeId}', encodeURIComponent(String(requestParameters['nodeId'])));
        urlPath = urlPath.replace('{newName}', encodeURIComponent(String(requestParameters['newName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceRenameNodeRaw(requestParameters: HeadscaleServiceRenameNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1RenameNodeResponse>> {
        const requestOptions = await this.headscaleServiceRenameNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1RenameNodeResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceRenameNode(requestParameters: HeadscaleServiceRenameNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1RenameNodeResponse> {
        const response = await this.headscaleServiceRenameNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceRenameUser without sending the request
     */
    async headscaleServiceRenameUserRequestOpts(requestParameters: HeadscaleServiceRenameUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['oldId'] == null) {
            throw new runtime.RequiredError(
                'oldId',
                'Required parameter "oldId" was null or undefined when calling headscaleServiceRenameUser().'
            );
        }

        if (requestParameters['newName'] == null) {
            throw new runtime.RequiredError(
                'newName',
                'Required parameter "newName" was null or undefined when calling headscaleServiceRenameUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user/{oldId}/rename/{newName}`;
        urlPath = urlPath.replace('{oldId}', encodeURIComponent(String(requestParameters['oldId'])));
        urlPath = urlPath.replace('{newName}', encodeURIComponent(String(requestParameters['newName'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async headscaleServiceRenameUserRaw(requestParameters: HeadscaleServiceRenameUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1RenameUserResponse>> {
        const requestOptions = await this.headscaleServiceRenameUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1RenameUserResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceRenameUser(requestParameters: HeadscaleServiceRenameUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1RenameUserResponse> {
        const response = await this.headscaleServiceRenameUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceSetApprovedRoutes without sending the request
     */
    async headscaleServiceSetApprovedRoutesRequestOpts(requestParameters: HeadscaleServiceSetApprovedRoutesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling headscaleServiceSetApprovedRoutes().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceSetApprovedRoutes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/node/{nodeId}/approve_routes`;
        urlPath = urlPath.replace('{nodeId}', encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HeadscaleServiceSetApprovedRoutesBodyToJSON(requestParameters['body']),
        };
    }

    /**
     */
    async headscaleServiceSetApprovedRoutesRaw(requestParameters: HeadscaleServiceSetApprovedRoutesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SetApprovedRoutesResponse>> {
        const requestOptions = await this.headscaleServiceSetApprovedRoutesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1SetApprovedRoutesResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceSetApprovedRoutes(requestParameters: HeadscaleServiceSetApprovedRoutesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SetApprovedRoutesResponse> {
        const response = await this.headscaleServiceSetApprovedRoutesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceSetPolicy without sending the request
     */
    async headscaleServiceSetPolicyRequestOpts(requestParameters: HeadscaleServiceSetPolicyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceSetPolicy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/policy`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: V1SetPolicyRequestToJSON(requestParameters['body']),
        };
    }

    /**
     */
    async headscaleServiceSetPolicyRaw(requestParameters: HeadscaleServiceSetPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SetPolicyResponse>> {
        const requestOptions = await this.headscaleServiceSetPolicyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1SetPolicyResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceSetPolicy(requestParameters: HeadscaleServiceSetPolicyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SetPolicyResponse> {
        const response = await this.headscaleServiceSetPolicyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for headscaleServiceSetTags without sending the request
     */
    async headscaleServiceSetTagsRequestOpts(requestParameters: HeadscaleServiceSetTagsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nodeId'] == null) {
            throw new runtime.RequiredError(
                'nodeId',
                'Required parameter "nodeId" was null or undefined when calling headscaleServiceSetTags().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling headscaleServiceSetTags().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/node/{nodeId}/tags`;
        urlPath = urlPath.replace('{nodeId}', encodeURIComponent(String(requestParameters['nodeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HeadscaleServiceSetTagsBodyToJSON(requestParameters['body']),
        };
    }

    /**
     */
    async headscaleServiceSetTagsRaw(requestParameters: HeadscaleServiceSetTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SetTagsResponse>> {
        const requestOptions = await this.headscaleServiceSetTagsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1SetTagsResponseFromJSON(jsonValue));
    }

    /**
     */
    async headscaleServiceSetTags(requestParameters: HeadscaleServiceSetTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SetTagsResponse> {
        const response = await this.headscaleServiceSetTagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
